<form>
    <fieldset>
        <legend>Mokykla</legend>
        <label>Mokyklos pavadinimas:</label><input name="name"/>
    </fieldset>
    <fieldset>
        <legend>Mokyklos administratorius</legend>
        <label>Administratoriaus ID:</label><input name="id"/>
        <label>Vardas ir pavardė:</label><input name="full_name"/>
        <label>Slaptažodis:</label><input name="password" type="password"/>
    </fieldset>
    <input type="submit" value="Pridėti"/>
</form>