<!DOCTYPE html>
    <html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <script src="script.js" type="text/javascript"></script>
    <link href="style.css" type="text/css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
    <title>Elektroninis dienynas v1.0</title>
</head>
<body>
<div id="wrapper">
<header></header>
<div id="body">
